# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    container: golang:1.22
    runs-on: ubuntu-latest

    env:
      GITHUB_TEST_RUN: "true"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

      minio:
        image: savchenkoim/minio
        ports:
          - 9000:9000

    steps:
      - uses: actions/checkout@v4

      - name: Something_Strange
        run: git config --global --add safe.directory '*'

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v ./...
